development:
  adapter: postgresql
  encoding: utf8
  database: festivalize_development
  pool: 5
  username: 
  password:

test:
  adapter: postgresql
  encoding: utf8
  database: festivalize_test
  pool: 5
  username: 
  password:

production:
  adapter: postgresql
  encoding: utf8
  database: festivalize_production
  pool: 5
  username: 
  password:
